#!/bin/sh -e
cat << EOT > /services/ss/ss.conf
{
    "server": "${SS_SERVER}",  
    "server_port": ${SS_SERVER_PORT},
    "password":"${SS_PASSWORD}",
    "local_address": "0.0.0.0",
    "local_port":${SS_PORT},
    "method":"${SS_METHOD}",
    "timeout":600
}
EOT
exec /usr/bin/ss-local -c ss.conf --plugin obfs-local --plugin-opts "obfs=http;obfs-host=${SS_OBFS_HOST}"
